@extends('layouts.app')

@section('title', 'Détail de la prévision')
@section('page_title', 'Détail de la prévision')

@section('content')
    <div class="mx-auto max-w-5xl space-y-8">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div class="flex items-center gap-3"><a href="{{ route('depense-previsions.index') }}" class="flex h-10 w-10 items-center justify-center rounded-2xl border border-slate-200 bg-white text-slate-500 transition hover:border-indigo-200 hover:text-indigo-600" aria-label="Retour"><i class="fa-solid fa-arrow-left"></i></a><div><p class="text-sm font-medium text-indigo-600">Vue détaillée</p><h2 class="mt-1 text-2xl font-bold tracking-tight text-slate-950">{{ $prevision->description }}</h2></div></div><div class="flex flex-wrap gap-3 pl-[52px] sm:pl-0"><x-prevision-validate-button :prevision="$prevision" /><a href="{{ route('depense-previsions.edit', $prevision) }}" class="inline-flex flex-1 items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-600 transition hover:border-indigo-200 hover:text-indigo-600 sm:flex-none"><i class="fa-solid fa-pen-to-square"></i>Modifier</a><form action="{{ route('depense-previsions.destroy', $prevision) }}" method="POST" data-delete-prevision="{{ $prevision->description }}" class="flex-1 sm:flex-none">@csrf @method('DELETE')<button type="submit" class="inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-600 transition hover:bg-rose-100"><i class="fa-solid fa-trash-can"></i>Supprimer</button></form></div></div>
        <section class="overflow-hidden rounded-3xl border border-slate-200/80 bg-white shadow-sm shadow-slate-200/40"><div class="bg-gradient-to-br from-slate-950 via-slate-900 to-indigo-950 px-6 py-8 text-white sm:px-10 sm:py-10"><div class="flex flex-col justify-between gap-6 sm:flex-row sm:items-start"><div><p class="text-sm font-medium text-slate-300">Montant prévu</p><p class="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">{{ number_format((float) $prevision->montant_previsionnel, 2, ',', ' ') }} <span class="text-xl font-semibold text-indigo-300">FC</span></p></div><x-prevision-status-badge :statut="$prevision->statut" /></div></div><div class="grid gap-6 p-6 sm:grid-cols-3 sm:p-10"><div class="rounded-2xl border border-slate-100 bg-slate-50 p-5"><div class="flex items-center gap-3 text-slate-400"><i class="fa-solid fa-tags"></i><span class="text-xs font-semibold uppercase tracking-[0.16em]">Catégorie</span></div><p class="mt-3 text-lg font-bold text-slate-950">{{ $prevision->categorie?->nom_categorie ?? 'Sans catégorie' }}</p></div><div class="rounded-2xl border border-slate-100 bg-slate-50 p-5"><div class="flex items-center gap-3 text-slate-400"><i class="fa-regular fa-calendar"></i><span class="text-xs font-semibold uppercase tracking-[0.16em]">Date prévue</span></div><p class="mt-3 text-lg font-bold text-slate-950">{{ $prevision->date_previsionnelle->format('d/m/Y') }}</p></div><div class="rounded-2xl border border-slate-100 bg-slate-50 p-5"><div class="flex items-center gap-3 text-slate-400"><i class="fa-solid fa-align-left"></i><span class="text-xs font-semibold uppercase tracking-[0.16em]">Description</span></div><p class="mt-3 text-sm font-semibold leading-6 text-slate-700">{{ $prevision->description }}</p></div></div></section>
        <section class="rounded-3xl border border-indigo-100 bg-indigo-50/60 p-6 sm:p-8"><div class="flex gap-4"><div class="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-white text-indigo-600 shadow-sm"><i class="fa-solid fa-chart-line"></i></div><div><h3 class="font-bold text-slate-950">État de la prévision</h3><p class="mt-1 text-sm leading-6 text-slate-600">Cette dépense est <strong>{{ strtolower($prevision->statut) }}</strong>. Le statut est calculé automatiquement à partir de sa date prévue.</p></div></div></section>
    </div>
@endsection
